### ISSUE TITLE
can't start new thread

### ISSUE THREAD

**Issue by argento81** [palahsu/DDoS-Ripper#18]
Traceback (most recent call last):
  File "DRipper.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 198, in <module>
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
root@pihole2:/home/misol/DDoS-Ripper# python3 -V
Python 3.7.3

**Comment by Thor-** [comment]
Maybe the same error:
```
root@vobave8723:~/DDoS-Ripper# python3 DRipper.py
Traceback (most recent call last):
  File "DRipper.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 11, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 3-9: ordinal not in range(256)
```

**Comment by ymikhailenko** [comment]
Same error on Raspberry Pi

**Comment by steelpuxnastik** [comment]
> Same error on Raspberry Pi
Use 64bit system.
It will not work on 32-bit system because of problems of 32bit ARM-realization of Python at this moment. On 64bit system it works great.
